import {
    writable
} from "svelte/store";

export const loggedIn = writable(false)
export const userDetails = writable()
export const courses = writable(
    [
        "BACHELOR OF ARTS (PSYCHOLOGY, SOCIOLOGY & POLITICAL SCIENCE)",
        "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "BACHELOR OF SCIENCE IN INDUSTRIAL CHEMISTRY",
        "BACHELOR OF SCIENCE IN ANALYTICAL CHEMISTRY",
        "BACHELOR OF SCIENCE IN COMPUTER SCIENCE",
        "BACHELOR OF SCIENCE IN CIVIL ENGINEERING",
        "BACHELOR OF COMMERCE",
        "BACHELOR OF SCIENCE IN ECONOMICS",
        "BACHELOR OF JOURNALISM",
        "BACHELOR OF SCIENCE (COMPUTER TECHNOLOGY)",
        "BACHELOR OF SCIENCE IN MECHANICAL AND MANUFACTURING ENGINEERING",
        "BACHELOR OF SCIENCE (INSTRUMENTATION & CONTROL)",
        "BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY",
        "BACHELOR OF BUSINESS INFORMATION TECHNOLOGY	",
        "BACHELOR OF SCIENCE IN ELECTRICAL AND TELECOMMUNICATION ENGINEERING",
        "BACHELOR OF PROCUREMENT AND LOGISTICS MANAGEMENT",
        "BACHELOR OF SCIENCE IN MATHEMATICS AND COMPUTER SCIENCE",
        "BACHELOR OF APPLIED COMMUNICATION",
        "BACHELOR OF SCIENCE IN SOFTWARE ENGINEERING",
        "BACHELOR OF SCIENCE IN APPLIED OPTICS AND LASERS",
        "BACHELOR OF SCIENCE IN RENEWABLE ENERGY AND TECHNOLOGY",
        "BACHELOR OF FILM AND ANIMATION",
        "BACHELOR OF SCIENCE IN APPLIED PHYSICS AND COMPUTER SCIENCE", "BACHELOR OF SCIENCE IN INDUSTRIAL CHEMISTRY",
        "BACHELOR OF SCIENCE IN ANALYTICAL CHEMISTRY",
        "BACHELOR OF COMMERCE",
        "BACHELOR OF SCIENCE (COMPUTER TECHNOLOGY)",
        "BACHELOR OF SCIENCE (INSTRUMENTATION & CONTROL)",
        "BACHELOR OF PROCUREMENT AND LOGISTICS MANAGEMENT",
        "BACHELOR OF SCIENCE IN APPLIED OPTICS AND LASERS",
        "BACHELOR OF SCIENCE IN RENEWABLE ENERGY AND TECHNOLOGY",
        "BACHELOR OF SCIENCE IN APPLIED PHYSICS AND COMPUTER SCIENCE"
    ]
)